### ISSUE TITLE
讨论一下分工

### ISSUE THREAD

**Issue by ylc395** [UESTC-FEDOG/Complex-page#1]
看了下，这个任务真的很复杂，一个人做得做疯掉，还是一起来开发吧！（等大家都有时间的时候

在这里讨论一下任务分工以及开发方式

**Comment by kkmikako** [comment]
**完成方式**按照IFE协作建议：
- 整体页面布局，整个顶部，右侧的面包屑，及右侧中间的两个第一组项目
- 整个左侧
- 右侧上面的前三部分：查询选项部分，价格显示部分，4月统计部分
- 右侧下方的2个模块，日历及表格

公用组件：
- 蓝色按钮
- 下拉菜单（Select）
- 右侧下方4个模块的面板样式

个人初步想法，对于这个任务我们可以真的尝试一次合作开发：
- 由cyl（她技术最好）写出模块化的html框架，定好主要类名,（大致布局也会由她完成？）大概形式如下：
  
  ```
  <body>
      <header>
      <section class="main">
      <section class="left">
      ....
      <footer>
  ```
- 分配任务完成以后我们每个人在自己的模块之中添加类名进行组合开发，每个单独模块的开发进度不影响其他开发人员的完成，最后开发完成直接合并完成
- 具体分配工作量请大家探讨下，我不能很好的确认

**Comment by ylc395** [comment]
页面的整体布局使用之前写过的grid系统来完成，总的来说是这种形式：
```html
<div class="col-md-*">
    <div>
    </div>
</div>
```

**Comment by ylc395** [comment]
页面的整体布局使用之前写过的grid系统来完成，总的来说是这种形式：

``` html
<div class="col-md-*">
    <div class="这里是组件的类名">
            组件的HTML结构
    </div>
</div>
```

每个领到写组件任务的人，最终应当提交自己编写好的CSS文件与图片（注意，不需要提交任何HTML文件），并在项目的[wiki页面](https://github.com/UESTC-FEDOG/Complex-page/wiki)按如下格式描述你编写的组件的用法，比如：

> 组件：xxxx
> 该组件的类名是xxx，要求的HTML结构如下：
> 
> ``` html
> <div class="xxx">
>     <li class="xxx-xxx">
>     <li class="xxx-xxx">
>     <li class="xxx-xxx">
> </div>
> ```

最后由一个人编写整个页面的HTML即可。命名风格可以参考BEM风格：
- http://www.w3cplus.com/css/bem-definitions.html
- http://www.w3cplus.com/css/mindbemding-getting-your-head-round-bem-syntax.html

至于分工，请继续讨论 @UESTC-FEDOG/fedogs 

下附设计图：

![](http://7xrp04.com1.z0.glb.clouddn.com/task_1_9_2.jpg)
